# Hands-on Exercise 2 — House Price Prediction (Data Preparation)

**DigiSkills AI Using Python** —  `HousePricePrediction.csv` next to this notebook, then `HousePricePrediction.csv` or `HousePricePrediction (2).csv` .

## 1. Dataset Loading 
- Load the dataset into a Pandas DataFrame
- Display the first 10 rows

In [4]:
import pandas as pd

df = pd.read_csv('datasets/HousePricePrediction_ml_ready.csv')

df.head(10)

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,208500.0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,20,9600,8,1976,1976,0.0,1262.0,181500.0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,60,11250,5,2001,2002,0.0,920.0,223500.0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,70,9550,5,1915,1970,0.0,756.0,140000.0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,60,14260,5,2000,2000,0.0,1145.0,250000.0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,50,14115,5,1993,1995,0.0,796.0,143000.0,0,0,...,0,0,0,0,0,0,0,1,0,0
6,20,10084,5,2004,2005,0.0,1686.0,307000.0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,60,10382,6,1973,1973,32.0,1107.0,200000.0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,50,6120,5,1931,1950,0.0,952.0,129900.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,190,7420,6,1939,1950,0.0,991.0,118000.0,0,0,...,0,0,0,1,0,0,0,0,0,0

## 2. Data Exploration :
- Shape of the dataset
- Data types of all columns
- Summary statistics of numerical features

In [5]:
print("Shape (rows, columns):", df.shape)
print()
print("Data types:")
print(df.dtypes)
print()
print("Summary statistics (numerical columns):")
df.describe()

Shape (rows, columns): (2919, 34)

Data types:
MSSubClass               int64
LotArea                  int64
OverallCond              int64
YearBuilt                int64
YearRemodAdd             int64
BsmtFinSF2             float64
TotalBsmtSF            float64
SalePrice              float64
MSZoning_FV              int64
MSZoning_RH              int64
MSZoning_RL              int64
MSZoning_RM              int64
LotConfig_CulDSac        int64
LotConfig_FR2            int64
LotConfig_FR3            int64
LotConfig_Inside         int64
BldgType_2fmCon          int64
BldgType_Duplex          int64
BldgType_Twnhs           int64
BldgType_TwnhsE          int64
Exterior1st_AsphShn      int64
Exterior1st_BrkComm      int64
Exterior1st_BrkFace      int64
Exterior1st_CBlock       int64
Exterior1st_CemntBd      int64
Exterior1st_HdBoard      int64
Exterior1st_ImStucc      int64
Exterior1st_MetalSd      int64
Exterior1st_Plywood      int64
Exterior1st_Stone        int64
Exterior1st_Stucco       int64
Exterior1st_VinylSd      int64
Exterior1st_Wd Sdng      int64
Exterior1st_WdShing      int64
dtype: object

Summary statistics (numerical columns):

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,...,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000
mean,57.137718,10168.114080,5.564577,1971.312778,1984.264474,49.565262,1051.756252,171963.667694,0.047619,0.008907,...,0.043165,0.151422,0.000343,0.154162,0.075711,0.000685,0.014731,0.351490,0.140802,0.019185
std,42.517628,7886.996359,1.113131,30.291442,20.894344,169.179104,440.692234,56884.755906,0.212995,0.093973,...,0.203264,0.358521,0.018509,0.361166,0.264580,0.026171,0.120495,0.477518,0.347876,0.137197
min,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,20.000000,7478.000000,5.000000,1953.500000,1965.000000,0.000000,793.000000,163000.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,50.000000,9453.000000,5.000000,1973.000000,1993.000000,0.000000,989.500000,163000.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,70.000000,11570.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,163000.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## 3. Data Cleaning :
- Identify missing values
- Handle missing values appropriately
- Check and remove duplicate records if any

In [6]:
missing_per_column = df.isna().sum()
missing_nonzero = missing_per_column[missing_per_column > 0].sort_values(ascending=False)
print("Missing value counts (columns with at least one missing value):")
print(missing_nonzero if len(missing_nonzero) else "No missing values.")
print("\nTotal missing cells:", int(df.isna().sum().sum()))

Missing value counts (columns with at least one missing value):
No missing values.

Total missing cells: 0

In [7]:
df_clean = df.copy()

num_cols = df_clean.select_dtypes(include=["number"]).columns
cat_cols = df_clean.select_dtypes(exclude=["number"]).columns

for c in num_cols:
    if df_clean[c].isna().any():
        df_clean[c] = df_clean[c].fillna(df_clean[c].median())

for c in cat_cols:
    if df_clean[c].isna().any():
        mode = df_clean[c].mode(dropna=True)
        fill = mode.iloc[0] if len(mode) else "Unknown"
        df_clean[c] = df_clean[c].fillna(fill)

print("Missing values after imputation:", int(df_clean.isna().sum().sum()))

dup_before = df_clean.duplicated().sum()
print("Duplicate rows (before removal):", int(dup_before))
df_clean = df_clean.drop_duplicates().reset_index(drop=True)
print("Shape after removing duplicates:", df_clean.shape)

Missing values after imputation: 0
Duplicate rows (before removal): 8
Shape after removing duplicates: (2911, 34)

## 4. Feature Selection (Marks 2)
- Identify relevant features for analysis
- Remove unnecessary identifier columns (e.g. `Id`)

We keep property and sale-related attributes and drop `Id`, which is not predictive.

In [8]:
cols_to_drop = [c for c in ["Id", "id"] if c in df_clean.columns]
df_features = df_clean.drop(columns=cols_to_drop, errors="ignore")

print("Dropped columns:", cols_to_drop if cols_to_drop else "(none named Id/id)")
print("Remaining columns:", df_features.shape[1])
print(list(df_features.columns[:15]), "...")

Dropped columns: (none named Id/id)
Remaining columns: 34
['MSSubClass', 'LotArea', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'BsmtFinSF2', 'TotalBsmtSF', 'SalePrice', 'MSZoning_FV', 'MSZoning_RH', 'MSZoning_RL', 'MSZoning_RM', 'LotConfig_CulDSac', 'LotConfig_FR2', 'LotConfig_FR3'] ...

## 5. Data Preprocessing (Marks 2)
- Encode categorical variables as numbers (one-hot encoding)
- Preview the dataset ready for machine learning

In [9]:
X_cat = df_features.select_dtypes(include=["object", "category"]).columns
df_ml = pd.get_dummies(df_features, columns=list(X_cat), drop_first=True, dtype=int)

print("ML-ready shape:", df_ml.shape)
print("All columns are numeric:", df_ml.select_dtypes(exclude=["number"]).shape[1] == 0)
df_ml.head(10)

ML-ready shape: (2911, 34)
All columns are numeric: True

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,208500.0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,20,9600,8,1976,1976,0.0,1262.0,181500.0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,60,11250,5,2001,2002,0.0,920.0,223500.0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,70,9550,5,1915,1970,0.0,756.0,140000.0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,60,14260,5,2000,2000,0.0,1145.0,250000.0,0,0,...,0,0,0,0,0,0,0,1,0,0
5,50,14115,5,1993,1995,0.0,796.0,143000.0,0,0,...,0,0,0,0,0,0,0,1,0,0
6,20,10084,5,2004,2005,0.0,1686.0,307000.0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,60,10382,6,1973,1973,32.0,1107.0,200000.0,0,0,...,0,1,0,0,0,0,0,0,0,0
8,50,6120,5,1931,1950,0.0,952.0,129900.0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,190,7420,6,1939,1950,0.0,991.0,118000.0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [11]:
# save cleaned + encoded data for Exercise 3 :

OUTPUT_CSV = "HousePricePrediction_ml_ready.csv"
df_ml.to_csv(OUTPUT_CSV, index=False)
print("Saved:", OUTPUT_CSV)

Saved: HousePricePrediction_ml_ready.csv