In [1]:
# There are two types of encoding categorial/Objecr tyope values :
# 1.Lable encoding
# 2. One heart encoding

from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
import pandas as pd

data = {
    'Student_Name': ['Ali', 'Sara', 'Ahmed', 'Ayesha', 'Bilal', 'Sana', 'Usman', 'Hina',
                      'Hamza', 'Zara', 'Fahad', 'Mahnoor', 'Imran', 'Rabia', 'Kamran',
                      'Nadia', 'Waqas', 'Sadia', 'Talha', 'Iqra', 'Salman', 'Amna',
                      'Junaid', 'Farah', 'Rizwan', 'Sobia', 'Adeel', 'Uzma', 'Danish', 'Mehak'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female',
               'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male',
               'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female',
               'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Marks': [92, 45, 67, 38, 81, 55, 29, 74, 88, 60, 33, 95, 50, 42, 77,
              25, 68, 90, 58, 35, 84, 62, 47, 73, 20, 99, 53, 66, 40, 85],
    'Attendance(%)': [95, 80, 88, 65, 92, 78, 55, 85, 96, 82, 60, 98, 75, 68, 89,
                       50, 84, 94, 79, 62, 90, 81, 70, 87, 45, 97, 76, 83, 71, 91],
    'Grade': ['A', 'D', 'C', 'F', 'B', 'C', 'F', 'B', 'A', 'C', 'F', 'A', 'C', 'D', 'B',
              'F', 'C', 'A', 'C', 'F', 'B', 'C', 'D', 'B', 'F', 'A', 'C', 'C', 'D', 'A'],
    'Status': ['Pass', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass',
               'Fail', 'Pass', 'Pass', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Fail',
               'Pass', 'Pass', 'Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass'],
    'Current Degree' : ["BS-IT", "BS-CS", "BS-DS", "BS-ML", "BS-AI", "BS-CS", "BS-DS", "BS-ML", "BS-AI", "BS-CS",
                        "BS-IT", "BS-CS", "BS-DS", "BS-DS", "BS-ML", "BS-AI", "BS-IT", "BS-CS", "BS-DS", "BS-CS",
                        "BS-CS", "BS-DS", "BS-ML", "BS-AI", "BS-CS", "BS-ML", "BS-AI", "BS-IT", "BS-CS", "BS-DS"],
    'City' : ["Lahore", "Islamabad", "Karachi", "Sialkot", "Islamabad", "Karachi", "Lahore", "Islamabad",
              "Islamabad", "Karachi", "Lahore", "Islamabad", "Karachi", "Lahore", "Sialkot", "Sialkot", 
              "Islamabad", "Karachi", "Lahore", "Islamabad", "Lahore", "Sialkot",  "Islamabad", "Karachi",
              "Lahore", "Islamabad", "Karachi", "Karachi", "Sialkot", "Islamabad" ]
        
    
}

df3 = pd.DataFrame(data)

In [5]:
df3.to_csv('cleandata_set2.csv')

In [20]:
df_label = df3.copy()

In [21]:
df_label

,Student_Name,Gender,Marks,Attendance(%),Grade,Status,Current Degree,City
0,Ali,Male,92,95,A,Pass,BS-IT,Lahore
1,Sara,Female,45,80,D,Pass,BS-CS,Islamabad
2,Ahmed,Male,67,88,C,Pass,BS-DS,Karachi
3,Ayesha,Female,38,65,F,Fail,BS-ML,Sialkot
4,Bilal,Male,81,92,B,Pass,BS-AI,Islamabad
5,Sana,Female,55,78,C,Pass,BS-CS,Karachi
6,Usman,Male,29,55,F,Fail,BS-DS,Lahore
7,Hina,Female,74,85,B,Pass,BS-ML,Islamabad
8,Hamza,Male,88,96,A,Pass,BS-AI,Islamabad
9,Zara,Female,60,82,C,Pass,BS-CS,Karachi
10,Fahad,Male,33,60,F,Fail,BS-IT,Lahore
11,Mahnoor,Female,95,98,A,Pass,BS-CS,Islamabad
12,Imran,Male,50,75,C,Pass,BS-DS,Karachi
13,Rabia,Female,42,68,D,Pass,BS-DS,Lahore
14,Kamran,Male,77,89,B,Pass,BS-ML,Sialkot
15,Nadia,Female,25,50,F,Fail,BS-AI,Sialkot
16,Waqas,Male,68,84,C,Pass,BS-IT,Islamabad
17,Sadia,Female,90,94,A,Pass,BS-CS,Karachi
18,Talha,Male,58,79,C,Pass,BS-DS,Lahore
19,Iqra,Female,35,62,F,Fail,BS-CS,Islamabad
20,Salman,Male,84,90,B,Pass,BS-CS,Lahore
21,Amna,Female,62,81,C,Pass,BS-DS,Sialkot
22,Junaid,Male,47,70,D,Pass,BS-ML,Islamabad
23,Farah,Female,73,87,B,Pass,BS-AI,Karachi
24,Rizwan,Male,20,45,F,Fail,BS-CS,Lahore
25,Sobia,Female,99,97,A,Pass,BS-ML,Islamabad
26,Adeel,Male,53,76,C,Pass,BS-AI,Karachi
27,Uzma,Female,66,83,C,Pass,BS-IT,Karachi
28,Danish,Male,40,71,D,Pass,BS-CS,Sialkot
29,Mehak,Female,85,91,A,Pass,BS-DS,Islamabad

In [22]:
# Now lets Apply "lable encoding" :

le = LabelEncoder()

In [23]:
df_label['Status_encoder'] = le.fit_transform(df_label["Status"])
df_label['Gender_encoder'] = le.fit_transform(df_label["Gender"])

In [24]:
print(f'''lets print the values of df_label['Student_Name'] ,df_label['Name_encoder'] , df_label["Gender"] , df_label['Gender_encoder'] :
{df_label[['Status', 'Status_encoder', "Gender", 'Gender_encoder']]}''')

lets print the values of df_label['Student_Name'] ,df_label['Name_encoder'] , df_label["Gender"] , df_label['Gender_encoder'] :
   Status  Status_encoder  Gender  Gender_encoder
0    Pass               1    Male               1
1    Pass               1  Female               0
2    Pass               1    Male               1
3    Fail               0  Female               0
4    Pass               1    Male               1
5    Pass               1  Female               0
6    Fail               0    Male               1
7    Pass               1  Female               0
8    Pass               1    Male               1
9    Pass               1  Female               0
10   Fail               0    Male               1
11   Pass               1  Female               0
12   Pass               1    Male               1
13   Pass               1  Female               0
14   Pass               1    Male               1
15   Fail               0  Female               0
16   Pass               1    Male               1
17   Pass               1  Female               0
18   Pass               1    Male               1
19   Fail               0  Female               0
20   Pass               1    Male               1
21   Pass               1  Female               0
22   Pass               1    Male               1
23   Pass               1  Female               0
24   Fail               0    Male               1
25   Pass               1  Female               0
26   Pass               1    Male               1
27   Pass               1  Female               0
28   Pass               1    Male               1
29   Pass               1  Female               0

In [25]:
# One-Hot encoding :

df3_encoded = pd.get_dummies(df3, columns=['City'])

print('\nOne-Hot encoded data (City) :' )
print(df3_encoded)

One-Hot encoded data (City) :
   Student_Name  Gender  Marks  Attendance(%) Grade Status Current Degree  \
0           Ali    Male     92             95     A   Pass          BS-IT
1          Sara  Female     45             80     D   Pass          BS-CS
2         Ahmed    Male     67             88     C   Pass          BS-DS
3        Ayesha  Female     38             65     F   Fail          BS-ML
4         Bilal    Male     81             92     B   Pass          BS-AI
5          Sana  Female     55             78     C   Pass          BS-CS
6         Usman    Male     29             55     F   Fail          BS-DS
7          Hina  Female     74             85     B   Pass          BS-ML
8         Hamza    Male     88             96     A   Pass          BS-AI
9          Zara  Female     60             82     C   Pass          BS-CS
10        Fahad    Male     33             60     F   Fail          BS-IT
11      Mahnoor  Female     95             98     A   Pass          BS-CS
12        Imran    Male     50             75     C   Pass          BS-DS
13        Rabia  Female     42             68     D   Pass          BS-DS
14       Kamran    Male     77             89     B   Pass          BS-ML
15        Nadia  Female     25             50     F   Fail          BS-AI
16        Waqas    Male     68             84     C   Pass          BS-IT
17        Sadia  Female     90             94     A   Pass          BS-CS
18        Talha    Male     58             79     C   Pass          BS-DS
19         Iqra  Female     35             62     F   Fail          BS-CS
20       Salman    Male     84             90     B   Pass          BS-CS
21         Amna  Female     62             81     C   Pass          BS-DS
22       Junaid    Male     47             70     D   Pass          BS-ML
23        Farah  Female     73             87     B   Pass          BS-AI
24       Rizwan    Male     20             45     F   Fail          BS-CS
25        Sobia  Female     99             97     A   Pass          BS-ML
26        Adeel    Male     53             76     C   Pass          BS-AI
27         Uzma  Female     66             83     C   Pass          BS-IT
28       Danish    Male     40             71     D   Pass          BS-CS
29        Mehak  Female     85             91     A   Pass          BS-DS

    City_Islamabad  City_Karachi  City_Lahore  City_Sialkot
0            False         False         True         False
1             True         False        False         False
2            False          True        False         False
3            False         False        False          True
4             True         False        False         False
5            False          True        False         False
6            False         False         True         False
7             True         False        False         False
8             True         False        False         False
9            False          True        False         False
10           False         False         True         False
11            True         False        False         False
12           False          True        False         False
13           False         False         True         False
14           False         False        False          True
15           False         False        False          True
16            True         False        False         False
17           False          True        False         False
18           False         False         True         False
19            True         False        False         False
20           False         False         True         False
21           False         False        False          True
22            True         False        False         False
23           False          True        False         False
24           False         False         True         False
25            True         False        False         False
26           False          True        False         False
27           False          True        False         False
28           False         False        False          True
29            True         False        False         False

In [26]:
cols_to_convert = ['City_Islamabad', 'City_Karachi', 'City_Lahore', 'City_Sialkot']

df3_encoded[cols_to_convert] = df3_encoded[cols_to_convert].astype(int)

In [27]:
df3_encoded

,Student_Name,Gender,Marks,Attendance(%),Grade,Status,Current Degree,City_Islamabad,City_Karachi,City_Lahore,City_Sialkot
0,Ali,Male,92,95,A,Pass,BS-IT,0,0,1,0
1,Sara,Female,45,80,D,Pass,BS-CS,1,0,0,0
2,Ahmed,Male,67,88,C,Pass,BS-DS,0,1,0,0
3,Ayesha,Female,38,65,F,Fail,BS-ML,0,0,0,1
4,Bilal,Male,81,92,B,Pass,BS-AI,1,0,0,0
5,Sana,Female,55,78,C,Pass,BS-CS,0,1,0,0
6,Usman,Male,29,55,F,Fail,BS-DS,0,0,1,0
7,Hina,Female,74,85,B,Pass,BS-ML,1,0,0,0
8,Hamza,Male,88,96,A,Pass,BS-AI,1,0,0,0
9,Zara,Female,60,82,C,Pass,BS-CS,0,1,0,0
10,Fahad,Male,33,60,F,Fail,BS-IT,0,0,1,0
11,Mahnoor,Female,95,98,A,Pass,BS-CS,1,0,0,0
12,Imran,Male,50,75,C,Pass,BS-DS,0,1,0,0
13,Rabia,Female,42,68,D,Pass,BS-DS,0,0,1,0
14,Kamran,Male,77,89,B,Pass,BS-ML,0,0,0,1
15,Nadia,Female,25,50,F,Fail,BS-AI,0,0,0,1
16,Waqas,Male,68,84,C,Pass,BS-IT,1,0,0,0
17,Sadia,Female,90,94,A,Pass,BS-CS,0,1,0,0
18,Talha,Male,58,79,C,Pass,BS-DS,0,0,1,0
19,Iqra,Female,35,62,F,Fail,BS-CS,1,0,0,0
20,Salman,Male,84,90,B,Pass,BS-CS,0,0,1,0
21,Amna,Female,62,81,C,Pass,BS-DS,0,0,0,1
22,Junaid,Male,47,70,D,Pass,BS-ML,1,0,0,0
23,Farah,Female,73,87,B,Pass,BS-AI,0,1,0,0
24,Rizwan,Male,20,45,F,Fail,BS-CS,0,0,1,0
25,Sobia,Female,99,97,A,Pass,BS-ML,1,0,0,0
26,Adeel,Male,53,76,C,Pass,BS-AI,0,1,0,0
27,Uzma,Female,66,83,C,Pass,BS-IT,0,1,0,0
28,Danish,Male,40,71,D,Pass,BS-CS,0,0,0,1
29,Mehak,Female,85,91,A,Pass,BS-DS,1,0,0,0

In [28]:
# I also Apply One-Hot encoding on any object(string) based column like Current Degree :
df3_encoded_cp = df3_encoded.copy()

df3_encoded2 = pd.get_dummies(df3_encoded, columns=['Current Degree'], dtype=int)

In [16]:
df3_encoded2

,Student_Name,Gender,Marks,Attendance(%),Grade,Status,City_Islamabad,City_Karachi,City_Lahore,City_Sialkot,Current Degree_BS-AI,Current Degree_BS-CS,Current Degree_BS-DS,Current Degree_BS-IT,Current Degree_BS-ML
0,Ali,Male,92,95,A,Pass,0,0,1,0,0,0,0,1,0
1,Sara,Female,45,80,D,Pass,1,0,0,0,0,1,0,0,0
2,Ahmed,Male,67,88,C,Pass,0,1,0,0,0,0,1,0,0
3,Ayesha,Female,38,65,F,Fail,0,0,0,1,0,0,0,0,1
4,Bilal,Male,81,92,B,Pass,1,0,0,0,1,0,0,0,0
5,Sana,Female,55,78,C,Pass,0,1,0,0,0,1,0,0,0
6,Usman,Male,29,55,F,Fail,0,0,1,0,0,0,1,0,0
7,Hina,Female,74,85,B,Pass,1,0,0,0,0,0,0,0,1
8,Hamza,Male,88,96,A,Pass,1,0,0,0,1,0,0,0,0
9,Zara,Female,60,82,C,Pass,0,1,0,0,0,1,0,0,0
10,Fahad,Male,33,60,F,Fail,0,0,1,0,0,0,0,1,0
11,Mahnoor,Female,95,98,A,Pass,1,0,0,0,0,1,0,0,0
12,Imran,Male,50,75,C,Pass,0,1,0,0,0,0,1,0,0
13,Rabia,Female,42,68,D,Pass,0,0,1,0,0,0,1,0,0
14,Kamran,Male,77,89,B,Pass,0,0,0,1,0,0,0,0,1
15,Nadia,Female,25,50,F,Fail,0,0,0,1,1,0,0,0,0
16,Waqas,Male,68,84,C,Pass,1,0,0,0,0,0,0,1,0
17,Sadia,Female,90,94,A,Pass,0,1,0,0,0,1,0,0,0
18,Talha,Male,58,79,C,Pass,0,0,1,0,0,0,1,0,0
19,Iqra,Female,35,62,F,Fail,1,0,0,0,0,1,0,0,0
20,Salman,Male,84,90,B,Pass,0,0,1,0,0,1,0,0,0
21,Amna,Female,62,81,C,Pass,0,0,0,1,0,0,1,0,0
22,Junaid,Male,47,70,D,Pass,1,0,0,0,0,0,0,0,1
23,Farah,Female,73,87,B,Pass,0,1,0,0,1,0,0,0,0
24,Rizwan,Male,20,45,F,Fail,0,0,1,0,0,1,0,0,0
25,Sobia,Female,99,97,A,Pass,1,0,0,0,0,0,0,0,1
26,Adeel,Male,53,76,C,Pass,0,1,0,0,1,0,0,0,0
27,Uzma,Female,66,83,C,Pass,0,1,0,0,0,0,0,1,0
28,Danish,Male,40,71,D,Pass,0,0,0,1,0,1,0,0,0
29,Mehak,Female,85,91,A,Pass,1,0,0,0,0,0,1,0,0